app_config:
  name: gen-SFT-Dataset
  version: 0.0.2
  description: Generate SFT Dataset
  adapters:
    - type: openai
      api_key: api_key
      model: gpt-4o
      temperature: 1.0
      top_p: 0.8
    - type: model_scope
      api_key: api_key
      model: qwen-turbo
      temperature: 1.0
      top_p: 0.8
  mysql:
    user: root
    password: 121511
    host: 127.0.0.1:3306
    db_name: gen_sft_dataset
